spring:
  application:
    name: sharing-community-ui
#  security:
#    user:
#      name: admin
#      password: 1234
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/plantorydb
    username: pldbid
    password: pldbpw
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

server:
  port: 5454

plant:
  api:
    base-url: http://api.nongsaro.go.kr/service/garden/gardenDtl
    key: 20251110HDUJPYCT3K8ZSKCRQQMSJW